name: Java CI with Gradle

on:
  push:
    branches: [ feature/add-ci-cd-pipeline ]
  pull_request:
    branches: [ feature/add-ci-cd-pipeline ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Clean, build, test, and generate coverage report
      run: ./gradlew clean build jacocoTestReport

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: test-results
        path: build/test-results/test

    - name: Upload code coverage report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: coverage-report
        path: build/reports/jacoco/test/html
